export enum JOTFORMFieldType {
  ControlHead = "control_head",
  ControlRadio = "control_radio",
  ControlDropdown = "control_dropdown",
  ControlPhone = "control_phone",
  ControlNumber = "control_number",
  ControlTextbox = "control_textbox",
  ControlPageBreak = "control_pagebreak",
  ControlFullname = "control_fullname",
  ControlEmail = "control_email",
  ControlAddress = "control_address",
  ControlDate = "control_datetime",
  ControlFileUpload = "control_fileupload",
  ControlTextarea = "control_textarea",
  ControlButton = "control_button",
  ControlHidden = "control_hidden",
}

export enum Gender {
  Male,
  Female,
}

export const applyGenderOptions = Object.entries(Gender)
  .filter(([key, value]) => !isNaN(Number(value)))
  .map(([key, value]) => ({
    label: key,
    value: value.toString(),
  }));

export enum EnglishProficiency {
  Excellent,
  Good,
  Average,
  None,
}

export const applyForEnglishProficiencyOptions = Object.keys(EnglishProficiency)
  .filter((key) => isNaN(Number(key)))
  .map((key, value) => ({
    label: key,
    value: value.toString(),
  }));

export enum ApplyForAcademicYear {
  Year2024,
  Year2025,
  Year2026,
}

export const applyForAcademicYearOptions = Object.keys(ApplyForAcademicYear)
  .filter((key) => isNaN(Number(key)))
  .map((key, value) => ({
    label: key.replace("Year", ""),
    value: value.toString(),
  }));

export enum IntakeTerm {
  Semester1,
  Semester2,
  Semester3,
}

export const applyForIntakeTermsOptions = Object.keys(IntakeTerm)
  .filter((key) => isNaN(Number(key)))
  .map((key, value) => ({
    label: key.replace("Semester", "Semester "),
    value: value.toString(),
  }));

export enum CurrentLivingStatus {
  Parents,
  Father,
  Mother,
  Guardian,
}

export const applyForCurrentLivingStatusOptions = Object.keys(CurrentLivingStatus)
  .filter((key) => isNaN(Number(key)))
  .map((key, value) => ({
    label: key,
    value: value.toString(),
  }));

export enum BloodType {
  A,
  B,
  AB,
  O,
}

export const applyForBloodTypeOptions = Object.keys(BloodType)
  .filter((key) => isNaN(Number(key)))
  .map((key, value) => ({
    label: key,
    value: value.toString(),
  }));

export enum IncomingGrade {
  Nursery1 = "Nursery 1",
  Nursery2 = "Nursery 2",
  K1 = "K1",
  K2 = "K2",
  Grade1 = "Grade 1",
  Grade2 = "Grade 2",
  Grade3 = "Grade 3",
  Grade4 = "Grade 4",
  Grade5 = "Grade 5",
  Grade6 = "Grade 6",
  Grade7 = "Grade 7",
  Grade8 = "Grade 8",
  Grade9 = "Grade 9",
  Grade10 = "Grade 10",
  Grade11 = "Grade 11",
  Grade12 = "Grade 12",
}

export enum Nationality {
  Afghan = "Afghan",
  Albanian = "Albanian",
  Algerian = "Algerian",
  American = "American",
  Andorran = "Andorran",
  Angolan = "Angolan",
  Anguillan = "Anguillan",
  Argentine = "Argentine",
  Armenian = "Armenian",
  Australian = "Australian",
  Austrian = "Austrian",
  Azerbaijani = "Azerbaijani",
  Bahamian = "Bahamian",
  Bahraini = "Bahraini",
  Bangladeshi = "Bangladeshi",
  Barbadian = "Barbadian",
  Belarusian = "Belarusian",
  Belgian = "Belgian",
  Belizean = "Belizean",
  Beninese = "Beninese",
  Bermudian = "Bermudian",
  Bhutanese = "Bhutanese",
  Bolivian = "Bolivian",
  Botswanan = "Botswanan",
  Brazilian = "Brazilian",
  British = "British",
  BritishVirginIslander = "British Virgin Islander",
  Bruneian = "Bruneian",
  Bulgarian = "Bulgarian",
  Burkinan = "Burkinan",
  Burmese = "Burmese",
  Burundian = "Burundian",
  Cambodian = "Cambodian",
  Cameroonian = "Cameroonian",
  Canadian = "Canadian",
  CapeVerdean = "Cape Verdean",
  CaymanIslander = "Cayman Islander",
  CentralAfrican = "Central African",
  Chadian = "Chadian",
  Chilean = "Chilean",
  Chinese = "Chinese",
  CitizenOfAntiguaAndBarbuda = "Citizen of Antigua and Barbuda",
  CitizenOfBosniaAndHerzegovina = "Citizen of Bosnia and Herzegovina",
  CitizenOfGuineaBissau = "Citizen of Guinea-Bissau",
  CitizenOfKiribati = "Citizen of Kiribati",
  CitizenOfSeychelles = "Citizen of Seychelles",
  CitizenOfTheDominicanRepublic = "Citizen of the Dominican Republic",
  CitizenOfVanuatu = "Citizen of Vanuatu",
  Colombian = "Colombian",
  Comoran = "Comoran",
  CongoleseCongo = "Congolese (Congo)",
  CongoleseDRC = "Congolese (DRC)",
  CookIslander = "Cook Islander",
  CostaRican = "Costa Rican",
  Croatian = "Croatian",
  Cuban = "Cuban",
  Cymraes = "Cymraes",
  Cymro = "Cymro",
  Cypriot = "Cypriot",
  Czech = "Czech",
  Danish = "Danish",
  Djiboutian = "Djiboutian",
  Dominican = "Dominican",
  Dutch = "Dutch",
  EastTimorese = "East Timorese",
  Ecuadorean = "Ecuadorean",
  Egyptian = "Egyptian",
  Emirati = "Emirati",
  English = "English",
  EquatorialGuinean = "Equatorial Guinean",
  Eritrean = "Eritrean",
  Estonian = "Estonian",
  Ethiopian = "Ethiopian",
  Faroese = "Faroese",
  Fijian = "Fijian",
  Filipino = "Filipino",
  Finnish = "Finnish",
  French = "French",
  Gabonese = "Gabonese",
  Gambian = "Gambian",
  Georgian = "Georgian",
  German = "German",
  Ghanaian = "Ghanaian",
  Gibraltarian = "Gibraltarian",
  Greek = "Greek",
  Greenlandic = "Greenlandic",
  Grenadian = "Grenadian",
  Guamanian = "Guamanian",
  Guatemalan = "Guatemalan",
  Guinean = "Guinean",
  Guyanese = "Guyanese",
  Haitian = "Haitian",
  Honduran = "Honduran",
  HongKonger = "Hong Konger",
  Hungarian = "Hungarian",
  Icelandic = "Icelandic",
  Indian = "Indian",
  Indonesian = "Indonesian",
  Iranian = "Iranian",
  Iraqi = "Iraqi",
  Irish = "Irish",
  Israeli = "Israeli",
  Italian = "Italian",
  Ivorian = "Ivorian",
  Jamaican = "Jamaican",
  Japanese = "Japanese",
  Jordanian = "Jordanian",
  Kazakh = "Kazakh",
  Kenyan = "Kenyan",
  Kittitian = "Kittitian",
  Kosovan = "Kosovan",
  Kuwaiti = "Kuwaiti",
  Kyrgyz = "Kyrgyz",
  Lao = "Lao",
  Latvian = "Latvian",
  Lebanese = "Lebanese",
  Liberian = "Liberian",
  Libyan = "Libyan",
  Liechtensteiner = "Liechtensteiner",
  Lithuanian = "Lithuanian",
  Luxembourger = "Luxembourger",
  Macanese = "Macanese",
  Macedonian = "Macedonian",
  Malagasy = "Malagasy",
  Malawian = "Malawian",
  Malaysian = "Malaysian",
  Maldivian = "Maldivian",
  Malian = "Malian",
  Maltese = "Maltese",
  Marshallese = "Marshallese",
  Martiniquais = "Martiniquais",
  Mauritanian = "Mauritanian",
  Mauritian = "Mauritian",
  Mexican = "Mexican",
  Micronesian = "Micronesian",
  Moldovan = "Moldovan",
  Monegasque = "Monegasque",
  Mongolian = "Mongolian",
  Montenegrin = "Montenegrin",
  Montserratian = "Montserratian",
  Moroccan = "Moroccan",
  Mosotho = "Mosotho",
  Mozambican = "Mozambican",
  Namibian = "Namibian",
  Nauruan = "Nauruan",
  Nepalese = "Nepalese",
  NewZealander = "New Zealander",
  Nicaraguan = "Nicaraguan",
  Nigerian = "Nigerian",
  Nigerien = "Nigerien",
  Niuean = "Niuean",
  NorthernIrish = "Northern Irish",
  NorthKorean = "North Korean",
  Norwegian = "Norwegian",
  Omani = "Omani",
  Pakistani = "Pakistani",
  Palauan = "Palauan",
  Palestinian = "Palestinian",
  Panamanian = "Panamanian",
  PapuaNewGuinean = "Papua New Guinean",
  Paraguayan = "Paraguayan",
  Peruvian = "Peruvian",
  PitcairnIslander = "Pitcairn Islander",
  Polish = "Polish",
  Portuguese = "Portuguese",
  Prydeinig = "Prydeinig",
  PuertoRican = "Puerto Rican",
  Qatari = "Qatari",
  Romanian = "Romanian",
  Russian = "Russian",
  Rwandan = "Rwandan",
  Salvadorean = "Salvadorean",
  Sammarinese = "Sammarinese",
  Samoan = "Samoan",
  SaoTomean = "Sao Tomean",
  SaudiArabian = "Saudi Arabian",
  Scottish = "Scottish",
  Senegalese = "Senegalese",
  Serbian = "Serbian",
  SierraLeonean = "Sierra Leonean",
  Singaporean = "Singaporean",
  Slovak = "Slovak",
  Slovenian = "Slovenian",
  SolomonIslander = "Solomon Islander",
  Somali = "Somali",
  SouthAfrican = "South African",
  SouthKorean = "South Korean",
  SouthSudanese = "South Sudanese",
  Spanish = "Spanish",
  SriLankan = "Sri Lankan",
  Stateless = "Stateless",
  StHelenian = "St Helenian",
  StLucian = "St Lucian",
  Sudanese = "Sudanese",
  Surinamese = "Surinamese",
  Swazi = "Swazi",
  Swedish = "Swedish",
  Swiss = "Swiss",
  Syrian = "Syrian",
  Taiwanese = "Taiwanese",
  Tajik = "Tajik",
  Tanzanian = "Tanzanian",
  Thai = "Thai",
  Togolese = "Togolese",
  Tongan = "Tongan",
  Trinidadian = "Trinidadian",
  Tristanian = "Tristanian",
  Tunisian = "Tunisian",
  Turkish = "Turkish",
  Turkmen = "Turkmen",
  TurksAndCaicosIslander = "Turks and Caicos Islander",
  Tuvaluan = "Tuvaluan",
  Ugandan = "Ugandan",
  Ukrainian = "Ukrainian",
  UnitedArabEmirates = "United Arab Emirates",
  Uruguayan = "Uruguayan",
  Uzbek = "Uzbek",
  VaticanCitizen = "Vatican citizen",
  Venezuelan = "Venezuelan",
  Vietnamese = "Vietnamese",
  Vincentian = "Vincentian",
  Wallisian = "Wallisian",
  Welsh = "Welsh",
  Yemeni = "Yemeni",
  Zambian = "Zambian",
  Zimbabwean = "Zimbabwean",
}

export enum StudentSpokenLanguage {
  Bengali = "Bengali",
  Bhojpuri = "Bhojpuri",
  Burmese = "Burmese",
  EgyptianArabic = "Egyptian Arabic",
  English = "English",
  French = "French",
  Gujarati = "Gujarati",
  Hausa = "Hausa",
  Hindi = "Hindi",
  IranianPersian = "Iranian Persian",
  Italian = "Italian",
  Japanese = "Japanese",
  Javanese = "Javanese",
  Korean = "Korean",
  MandarinChinese = "Mandarin Chinese",
  Marathi = "Marathi",
  Portuguese = "Portuguese",
  Russian = "Russian",
  Spanish = "Spanish",
  StandardGerman = "Standard German",
  Tamil = "Tamil",
  Telugu = "Telugu",
  Thai = "Thai",
  Turkish = "Turkish",
  Urdu = "Urdu",
  Vietnamese = "Vietnamese",
  WesternPunjabi = "Western Punjabi",
  WuChinese = "Wu Chinese",
  YueChinese = "Yue Chinese",
}

export enum PreferredLanguage {
  Thai = "Thai",
  Japanese = "Japanese",
  Korean = "Korean",
  Chinese = "Chinese",
}

export enum StudentEnglishProficiency {
  Native = "Native",
  Fluent = "Fluent",
  Good = "Good",
  Fair = "Fair",
  None = "None",
}

export enum BoardingProgram {
  WeekDay = "5-Day Boarding Program (Weekday Stay)",
  FullWeekDay = "7-Day Boarding Program (Full Week Stay)",
}
