export function mapPathToBreadcrumb(pathname: string): string {
  const breadcrumbPaths = new Map<string, string>([
    ["about-us", "About Us"],
    ["admission", "Admission"],
    ["xcl-asb-story", "The XCL ASB Story"],
    ["head-of-school", "Head of School's Welcome"],
    ["vision-and-mission", "Vision & Mission"],
    ["history", "History of XCL ASB Sukhumvit"],
    ["our-team", "Our Team"],
    ["school-facilities", "School Facilities"],
    ["xcl-education", "XCL Education"],
    ["admission-and-process", "Admission and Process"],
    ["tuition-and-fees", "Tuition & Fees"],
    ["scholarship", "Scholarship"],
    ["admission-key-dates", "Admission Key Dates"],
    ["faq", "FAQ"],
    ["apply-now", "Apply Now"],
    ["pastoral-care", "Pastoral Care"],
    ["co-curricular-life", "Co-Curricular Life"],
    ["after-school-program", "After School Program"],
    ["summer-school-program", "Summer School Program"],
    ["sports", "Sports"],
    ["life-at-xcl-asb-sukhumvit", "Life At XCL ASB Sukhumvit"],
    ["university-preparation", "University Preparation"],
    ["field-trips", "Field Trips"],
    ["school-bus-service", "School Bus Service"],
    ["student-support", "Student Support"],
    ["safety-and-security", "Safety And Security"],
    ["school-uniform", "School Uniform"],
    ["performing-and-fine-arts", "Performance and Fine Arts"],
    ["community-outreach-program", "Community Outreach Programs"],
    ["holidays-and-celebrations", "Holidays and Celebrations"],
    ["academics-activities", "Academics activities"],
    ["academics-and-curriculum", "academics & curriculum"],
    ["our-community", "Our Community"],
    ["news", "News"],
    ["curriculum", "Academics and Curriculum"],
    ["work-with-us", "Work With Us"],
    ["advanced-placement", "advanced placement (AP)"],
    ["american-curriculum", "American Curriculum"],
    ["early-years-program", "Early Years Program"],
    ["elementary-program", "Elementary program"],
    ["english-language-learner-program", "English Language Learner (ELL) Program"],
    ["high-school-program", "High School Program"],
    ["middle-school-program", "Middle School Program"],
    ["project-based-learning-activities", "Project-Based Learning Activities"],
    ["the-xcl-asb-sukhumvit-family", "The XCL ASB Sukhumvit Family"],
    ["parent-involvement", "Parent Involvement"],
    ["success-stories", "Success stories"],
    ["our-voices", "Our Voices"],
    ["ages-guidelines-for-entry", "Age Guidelines for Entry"],
  ]);

  return breadcrumbPaths.get(pathname) || "Home";
}
